stages:
  preprocess:
    cmd: python3 ./classification_model/process_raw_data.py
    deps:
    - classification_model/process_raw_data.py
    - data/diabetes_raw.csv
    outs:
    - ./data/diabetes_raw_processed.csv
