stages:
  preprocess:
    cmd: python3 ./classification_model/process_raw_data.py
    deps:
    - classification_model/process_raw_data.py
    - data/diabetes_raw.csv
    outs:
    - ./data/diabetes_raw_processed.csv
  split_preprocess:
    cmd: python3 classification_model/split_preprocess.py
    deps:
    - classification_model/split_preprocess.py
    - data/diabetes_raw_processed.csv
    outs:
    - data/X_test.csv
    - data/X_train.csv
    - data/y_test.csv
    - data/y_train.csv
